evidence(a(1), true).
evidence(a(2), false).
evidence(a(3), false).
evidence(a(4), false).
evidence(a(5), false).
evidence(a(6), false).
evidence(c(1), false).
evidence(c(2), false).
evidence(c(3), true).
evidence(e(1), true).
evidence(e(2), false).
evidence(e(3), false).
evidence(e(4), false).
evidence(d(1), true).
evidence(d(2), false).
evidence(d(3), false).
evidence(d(4), false).
evidence(d(5), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(b(4), false).
evidence(b(5), false).
---
evidence(a(1), true).
evidence(a(2), false).
evidence(a(3), false).
evidence(a(4), false).
evidence(a(5), false).
evidence(a(6), false).
evidence(c(1), false).
evidence(c(2), true).
evidence(c(3), false).
evidence(e(1), false).
evidence(e(2), true).
evidence(e(3), false).
evidence(e(4), false).
evidence(d(1), true).
evidence(d(2), false).
evidence(d(3), false).
evidence(d(4), false).
evidence(d(5), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(b(4), false).
evidence(b(5), false).
---
evidence(a(1), false).
evidence(a(2), false).
evidence(a(3), true).
evidence(a(4), false).
evidence(a(5), false).
evidence(a(6), false).
evidence(c(1), false).
evidence(c(2), true).
evidence(c(3), false).
evidence(e(1), false).
evidence(e(2), true).
evidence(e(3), false).
evidence(e(4), false).
evidence(d(1), true).
evidence(d(2), false).
evidence(d(3), false).
evidence(d(4), false).
evidence(d(5), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(b(4), false).
evidence(b(5), false).
---
evidence(a(1), true).
evidence(a(2), false).
evidence(a(3), false).
evidence(a(4), false).
evidence(a(5), false).
evidence(a(6), false).
evidence(c(1), false).
evidence(c(2), true).
evidence(c(3), false).
evidence(e(1), false).
evidence(e(2), true).
evidence(e(3), false).
evidence(e(4), false).
evidence(d(1), true).
evidence(d(2), false).
evidence(d(3), false).
evidence(d(4), false).
evidence(d(5), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(b(4), false).
evidence(b(5), false).
---
evidence(a(1), true).
evidence(a(2), false).
evidence(a(3), false).
evidence(a(4), false).
evidence(a(5), false).
evidence(a(6), false).
evidence(c(1), false).
evidence(c(2), true).
evidence(c(3), false).
evidence(e(1), true).
evidence(e(2), false).
evidence(e(3), false).
evidence(e(4), false).
evidence(d(1), true).
evidence(d(2), false).
evidence(d(3), false).
evidence(d(4), false).
evidence(d(5), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(b(4), false).
evidence(b(5), false).
---
