evidence(a(1), false).
evidence(a(2), false).
evidence(a(3), true).
evidence(b(1), false).
evidence(b(2), false).
evidence(b(3), true).
evidence(c(1), false).
evidence(c(2), true).
evidence(c(3), false).
evidence(d(1), false).
evidence(d(2), true).
evidence(d(3), false).
evidence(e(1), false).
evidence(e(2), false).
evidence(e(3), true).
evidence(f(1), true).
evidence(f(2), false).
---
evidence(a(1), false).
evidence(a(2), false).
evidence(a(3), true).
evidence(b(1), false).
evidence(b(2), false).
evidence(b(3), true).
evidence(c(1), true).
evidence(c(2), false).
evidence(c(3), false).
evidence(d(1), false).
evidence(d(2), true).
evidence(d(3), false).
evidence(e(1), false).
evidence(e(2), false).
evidence(e(3), true).
evidence(f(1), true).
evidence(f(2), false).
---
evidence(a(1), true).
evidence(a(2), false).
evidence(a(3), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(c(1), false).
evidence(c(2), true).
evidence(c(3), false).
evidence(d(1), false).
evidence(d(2), false).
evidence(d(3), true).
evidence(e(1), true).
evidence(e(2), false).
evidence(e(3), false).
evidence(f(1), true).
evidence(f(2), false).
---
evidence(a(1), true).
evidence(a(2), false).
evidence(a(3), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(c(1), true).
evidence(c(2), false).
evidence(c(3), false).
evidence(d(1), true).
evidence(d(2), false).
evidence(d(3), false).
evidence(e(1), false).
evidence(e(2), true).
evidence(e(3), false).
evidence(f(1), true).
evidence(f(2), false).
---
evidence(a(1), false).
evidence(a(2), false).
evidence(a(3), true).
evidence(b(1), false).
evidence(b(2), false).
evidence(b(3), true).
evidence(c(1), true).
evidence(c(2), false).
evidence(c(3), false).
evidence(d(1), false).
evidence(d(2), false).
evidence(d(3), true).
evidence(e(1), false).
evidence(e(2), true).
evidence(e(3), false).
evidence(f(1), false).
evidence(f(2), true).
---
evidence(a(1), true).
evidence(a(2), false).
evidence(a(3), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(c(1), true).
evidence(c(2), false).
evidence(c(3), false).
evidence(d(1), true).
evidence(d(2), false).
evidence(d(3), false).
evidence(e(1), true).
evidence(e(2), false).
evidence(e(3), false).
evidence(f(1), true).
evidence(f(2), false).
---
evidence(a(1), false).
evidence(a(2), false).
evidence(a(3), true).
evidence(b(1), false).
evidence(b(2), false).
evidence(b(3), true).
evidence(c(1), true).
evidence(c(2), false).
evidence(c(3), false).
evidence(d(1), false).
evidence(d(2), false).
evidence(d(3), true).
evidence(e(1), false).
evidence(e(2), true).
evidence(e(3), false).
evidence(f(1), true).
evidence(f(2), false).
---
evidence(a(1), true).
evidence(a(2), false).
evidence(a(3), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(c(1), false).
evidence(c(2), true).
evidence(c(3), false).
evidence(d(1), false).
evidence(d(2), false).
evidence(d(3), true).
evidence(e(1), true).
evidence(e(2), false).
evidence(e(3), false).
evidence(f(1), false).
evidence(f(2), true).
---
evidence(a(1), false).
evidence(a(2), true).
evidence(a(3), false).
evidence(b(1), true).
evidence(b(2), false).
evidence(b(3), false).
evidence(c(1), true).
evidence(c(2), false).
evidence(c(3), false).
evidence(d(1), false).
evidence(d(2), true).
evidence(d(3), false).
evidence(e(1), false).
evidence(e(2), true).
evidence(e(3), false).
evidence(f(1), false).
evidence(f(2), true).
---
